### ISSUE TITLE
Create Deco java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by Tankonor** [ChosenArchitect/Project-Architect-2#146]
**Describe the bug**
Brand new install of Project Architect 2 (never installed before)
Picked default version 3.3
Crash on startup (can't even load the modpack to the game menu)
->

**To Reproduce**
1. Download the modpack afresh
2. Start it up
3. Crash
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.3
**Java Version**
-> "Recommended" - Java Version: 17.0.4, Eclipse Adoptium
**Modpack Launcher Used**
-> FTB App
**Ram Allocated**
-> 6132mb

**Additional context**
->
Full crash gist:
https://gist.github.com/Tankonor/750444867d78dea4a622b5d41c37f6c0

Mod file and version:
project architect 2/mods/createdeco-2.0.2-1.20.1-forge.jar

crash head:

```
-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?] {re:mixin}
-- MOD createdeco --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at com.github.talrey.createdeco.api.Catwalks.build(Catwalks.java:84) ~[createdeco-2.0.2-1.20.1-forge.jar%23534!/:?] {re:classloading}
		at com.github.talrey.createdeco.BlockRegistry.registerCatwalks(BlockRegistry.java:186) ~[createdeco-2.0.2-1.20.1-forge.jar%23534!/:?] {re:classloading}
		at java.util.HashMap.forEach(Unknown Source) ~[?:?] {re:mixin}
		at com.github.talrey.createdeco.BlockRegistry.init(BlockRegistry.java:102) ~[createdeco-2.0.2-1.20.1-forge.jar%23534!/:?] {re:classloading}
		at com.github.talrey.createdeco.CreateDecoMod.init(CreateDecoMod.java:17) ~[createdeco-2.0.2-1.20.1-forge.jar%23534!/:?] {re:classloading}
		at com.github.talrey.createdeco.forge.CreateDecoModForge.<init>(CreateDecoModForge.java:17) ~[createdeco-2.0.2-1.20.1-forge.jar%23534!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23776!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23775!/:?] {re:mixin}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}
```

**Comment by Tankonor** [comment]
Well, randomly, increasing the ram allocation from 6gb to 10gb solved the problem, despite the memory usage only being between 1 and 2gb out of 6gb at the time of the crash 😂
