### ISSUE TITLE
Server not stopping properly

### ISSUE THREAD

**Issue by Demsli** [ChosenArchitect/Project-Architect-2#232]
**Describe the bug**
-> When stopping the server - an error is thrown that the server failed to store the chunk. Due to this error the server window does not close properly. It did not happen from the start, started happening towards the midgame, when I popped into the Bumblezone.

**To Reproduce**
1. Might be a specific personal case. I have the error message below.

**Expected behavior**
-> Expected the server to close without any errors.

**Screenshots**
Here is the log of the error:
[02:45:12] [IO-Worker-15/ERROR] [minecraft/IOWorker]: Failed to store chunk [-496, -229]
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?] {}
        at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?] {}
        at net.minecraft.nbt.CompoundTag.m_6434_(CompoundTag.java:133) ~[server-1.20.1-20230612.114412-srg.jar%23719!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.nbt_memory_usage.CompoundTagMixin,pl:mixin:A}
        at net.minecraft.nbt.NbtIo.m_128950_(NbtIo.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23719!/:?] {re:classloading,re:mixin}
        at net.minecraft.nbt.NbtIo.m_128941_(NbtIo.java:108) ~[server-1.20.1-20230612.114412-srg.jar%23719!/:?] {re:classloading,re:mixin}
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.m_63708_(RegionFileStorage.java:79) ~[server-1.20.1-20230612.114412-srg.jar%23719!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.level.chunk.storage.IOWorker.m_63535_(IOWorker.java:260) ~[server-1.20.1-20230612.114412-srg.jar%23719!/:?] {re:mixin,re:classloading,pl:mixin:APP:hyperbox.mixins.json:IOWorkerMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.storage.IOWorker.m_63553_(IOWorker.java:250) ~[server-1.20.1-20230612.114412-srg.jar%23719!/:?] {re:mixin,re:classloading,pl:mixin:APP:hyperbox.mixins.json:IOWorkerMixin,pl:mixin:A}
        at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:60) ~[server-1.20.1-20230612.114412-srg.jar%23719!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23719!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23719!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23719!/:?] {re:classloading}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] {}
        at java.lang.Thread.run(Thread.java:842) ~[?:?] {re:mixin}

**Modpack version**
-> 4.0 (happened on 3.6 too)
**Java Version**
-> Java 17
**Modpack Launcher Used**
-> Dedicated Server
**Ram Allocated**
-> 12

**Additional context**
-> I checked the mentioned chunk. There is nothing in it. Just a chunk in the middle of nowhere. I added a few mods to the pack. But they did not produce this situation before. But here are the added mods:
- AEInfinityBooster-1.20.1-1.0.0+21
- AutoRestart-1.20.1-2.0.2
- hyperbox-1.20.1-4.0.2.0
- SimpleLogin-1.20.1-1.0.2-all
- teamprojecte-1.20.1-1.1.4

The bat file contents that start and close the server: cd "D:\Users\Server\Desktop\Project Architect 2 4.0 Server Files"
start java -Xmx12G @libraries/net/minecraftforge/forge/1.20.1-47.3.7/win_args.txt nogui

As mentioned before - can be an unlucky specific case. But will be glad to hear suggestions how to fix this:)

**Comment by zeziba** [comment]
I am getting the same issue, no additional anything just as it is. Also latest version I am using is 4.2

Also, not only does it fail to exit properly it hogs the CPU and does not release the memory of the game even when force closed.

Here is the log.


[latest.log](https://github.com/user-attachments/files/17085658/latest.log)

**Comment by IRicTheCoder** [comment]
**A Note:** You do not require AEInfinityBooster, AE2WT has the Quantum Bridge Card which does essentially the same.

As for the rest, I have not encountered this before, also @zeziba yours is not the same issue since the log doesn't show the same thing.

Recommendation for both is to update to 4.3, if it still happen please do post again here, thank you!

**Comment by zeziba** [comment]
@IRicTheCoder  Still was happening after the update, happens every time as well. Haven't spent the time to check it out but the game functions normally other than closing. I did a fresh update with only the save and options.txt moved over and it still does it as well.


[2024-09-23-1.log.gz](https://github.com/user-attachments/files/17121981/2024-09-23-1.log.gz)

**Comment by IRicTheCoder** [comment]
Have you gone to the chunk and check what is in there? There might be some corruption

**Comment by zeziba** [comment]
I normally use the same chunks, there is no log spam or anything to indicate a corruption.

I also ensure that I have minimal things inside my inventory, anything that is an armor/tool/weapon gets sorted out and put into a subsystem which I regularly flush through an IF disenchantment machine that then gets fed into either a apotheosis table or trash bin. As a result I do not have many items with nbt in my chunks.

**Comment by Demsli** [comment]
Paused my playthrough for a bit. Updated the server today to version 4.8. Still getting the same error when restarting. Guess my world just somehow got corrupted. Attached my latest log file just in case someone can figure out this mystery. The chunk coordinates in the log are clean the last time I checked and I dont have anything in there.
[latest (5).log](https://github.com/user-attachments/files/17688755/latest.5.log)
