### ISSUE TITLE
Stuck when Saving World

### ISSUE THREAD

**Issue by Snowyfreezer** [ChosenArchitect/Project-Architect-2#249]
**Describe the bug**
-> Whenever the world is started it works normally. When logging out of the world it seems to be stuck on the saving world screen. 

**To Reproduce**
1.  Start the world
2.  Exit the world
3. 
4. 

**Expected behavior**
-> The game should go back to the title screen after saving is finished.

**Screenshots**
If applicable, add 
screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/90bff93b-b28a-4e8d-8ccd-93a4252610d2)

**Modpack version**
-> 4.4
**Java Version**
-> 17.0.12.7
**Modpack Launcher Used**
-> Prism Launcher
**Ram Allocated**
-> 12288 mb

**Additional context**
-> 
Log file
[2024-09-26-12.log.gz](https://github.com/user-attachments/files/17156907/2024-09-26-12.log.gz)
https://pastebin.com/rvScGfAp

**Comment by IRicTheCoder** [comment]
Did you add any mods to the pack? If not break all your mekanism pipes that are of the type "Mechanical" that what is causing the error in the log. Try saving the world after that.

**Comment by Snowyfreezer** [comment]
It still seems to get stuck even after breaking this pipe 
![2024-09-27_13 04 50](https://github.com/user-attachments/assets/9bf38fbe-d063-49aa-8272-affb94b8eff8)

[2024-09-27-2.log.gz](https://github.com/user-attachments/files/17167794/2024-09-27-2.log.gz)

**Comment by Snowyfreezer** [comment]
[latest.log](https://github.com/user-attachments/files/17176165/latest.log)

Looks like something is wrong with a chunk?

```
[28Sep2024 15:56:17.371] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Stopping singleplayer server as player logged out
[28Sep2024 15:56:17.396] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[28Sep2024 15:56:17.396] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[28Sep2024 15:56:17.396] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[28Sep2024 16:01:24.433] [IO-Worker-17/ERROR] [net.minecraft.world.level.chunk.storage.IOWorker/]: Failed to store chunk [87, 7]
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
	at net.minecraft.nbt.CompoundTag.m_6434_(CompoundTag.java:133) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at net.minecraft.nbt.NbtIo.m_128950_(NbtIo.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at net.minecraft.nbt.NbtIo.m_128941_(NbtIo.java:108) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.m_63708_(RegionFileStorage.java:79) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at net.minecraft.world.level.chunk.storage.IOWorker.m_63535_(IOWorker.java:260) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at net.minecraft.world.level.chunk.storage.IOWorker.m_63553_(IOWorker.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:60) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

```

**Comment by IRicTheCoder** [comment]
Yeah that does seem related to the chunk itself, those are always hard to sort unfortunately, is the chunk being force loaded or claimed?

**Comment by Snowyfreezer** [comment]
I don't believe so, at least not anything in the overworld with those coordnates

**Comment by Snowyfreezer** [comment]
Well actually I'm not 100% sure on how to read and find the coordinates of that chunk

**Comment by Snowyfreezer** [comment]
oh I think I found the culprit
![2024-09-28_17 01 33](https://github.com/user-attachments/assets/1e4e9725-3654-4140-bb75-bad85e5ebf81)

World started saving normally when both are broken

**Comment by IRicTheCoder** [comment]
Guess we (you did) found it then, might be an issue with the Void Engines then, make sure it is working now, and get back to us

**Comment by Snowyfreezer** [comment]
![2024-09-28_17 24 07](https://github.com/user-attachments/assets/9d172214-654d-4f93-9ac1-dab359346bfd)
![2024-09-28_17 24 54](https://github.com/user-attachments/assets/18ed52b1-9030-4dc4-b1e4-5cd580aa1932)

Testing on a flat world, it seems like the Void motor's existence just causes it

**Comment by Snowyfreezer** [comment]
Works normally and returns to title properly!

![2024-09-28_17 37 38](https://github.com/user-attachments/assets/ce136c81-14d3-40b7-b6f3-ec22ad97b502)
![2024-09-28_17 37 49](https://github.com/user-attachments/assets/34cf9b18-5424-478c-a4c1-59c9fb518138)

**Comment by IRicTheCoder** [comment]
This is extremely helpful thank you, I will keep the issue open so we can look into it and see if there is a fix for it, or report it as an issue to the mod.

**Comment by IRicTheCoder** [comment]
Could not replicate this issue in testing, will add a tooltip to the motor saying it can cause TPS/Lag issues so people are warned it is a possibility. Will close the issue as solved since you did find the problem.
